export { default as Home } from './Home'
export { default as Tours } from './Tours'
export { default as Profile } from './Profile'
export { default as TourPlace } from './TourPlace'
export { default as Notification } from './Notification'
export { default as ReservedTours } from './ReservedTours'
export { default as PersonalInformation } from './PersonalInformation'
export { default as AccountInformation } from './AccountInformation'
export { default as ManagePrivacy } from './ManagePrivacy'
export { default as SignIn } from './Authentication/SignIn'
export { default as SignUp } from './Authentication/SignUp'
export { default as Welcome } from './OnBoarding/Welcome'
export { default as bookingsWithLogin } from './bookingsWithLogin'
export { default as OnBoarding } from './OnBoarding/OnBoarding'
export { default as Request } from './Request/Request'
export { default as SearchTours} from './SearchTours'
export { default as Help } from './Help'
export { default as About } from './About'
 